name: Build iOS Dylib
on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile Dylib
        run: |
          xcrun -sdk iphoneos clang -dynamiclib -arch arm64 main.m -o WipeData.dylib -framework UIKit -framework Foundation -framework Security
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyWipeDylib
          path: WipeData.dylib
